# Generated by Django 5.2.6 on 2025-09-16 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=50)),
                ('experience_years', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('consultation_fee', models.PositiveBigIntegerField(verbose_name='Consultation Fee (in local currency)')),
                ('available', models.BooleanField(default=False)),
                ('departments', models.ManyToManyField(related_name='doctors', to='hospitals.department')),
                ('hospitals', models.ManyToManyField(related_name='doctors', to='hospitals.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
